[[responsibilities]]
Responsibilities
----------------

* They describe what has happened in the system
* They describe what can happen in the system
* They are how we persist our domain objects
** By keeping track of everything that has happened.
* They are how we do data mining through
link:Complex_Event_Processing[Complex Event Processing]
* They are how we integrate with other systems
* They are what we generate our Query Models from

[[by-how-they-inherit-each-other-they-define-how-things-that-happen-in-the-domain-relate-to-each-other]]
By how they inherit each other they define how things that happen in the
domain relate to each other
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Does editing skills mean that skills have been added? Then the hierarchy
had better show this!

*It is hard to overstate the importance of making sure that we design
them well. We absolutely must ensure that they align with the domain as
well as we possibly can.*

*Since they are used for so many things they have a high degree of
coupling to other systems. This makes them quite hard to change without
breaking things.* *Getting the events right is the most important design
task we have.*

The way we manage the coupling and maintain the ability to change is
straight out of the SOLID playbook.

* SRP: We ensure that we extract every abstraction we can into its own
interface
* OCP: We ensure that we make every relationship concrete through
inheritance relationships so that things will not break when we add
events. We design our events so that once other systems use them we can
add all the functionality we need without changing event. Just by adding
new events.
* LSP: We make sure that the inheritance relationships are correct. We
must be very careful to put members in the correct interface.
* ISP: Need I say anything after we just described creating this
plethora of specific interfaces?
* DIP: What could be more abstract than the idea that something has
happened represented as an interface?

[[a-code-example]]
A Code example
--------------

`namespace GlobalEvents` +
`{` +
`  #region Generic events intended to be inherited. None of these should ever be raised. Only inheritors should be raised.` +
 +
`  //Every single CV event should inherit this one. Directly or indirectly.` +
`  public interface ICVEvent : IAggregateRootEvent {}` +
 +
`  //Note how this event inherits IAggregateRootCreatedEvent. This allows SingleAggregateQueryModelUpdater and others to automatically know that it is a creation event.` +
`  //Any event that signifies that a CV has been created should inherit this event` +
`  //That way SingleAggregateQueryModelUpdater will not try to read the model from the DB and it can automatically instantiate the model with the correct aggregate root id.` +
`  public interface ICVCreated : ICVEvent, IAggregateRootCreatedEvent {}` +
 +
`  //Note how this event inherits IAggregateRootDeletedEvent. This allows SingleAggregateQueryModelUpdater and others to automatically know that it is a delet`